// src/widgets/BaseLayout/ui/BaseLayout.tsx
import {ReactNode} from 'react';
import './BaseLayout.scss';
import {box, vstack} from 'generated/patterns';

type BaseLayoutProps = {
  children?: ReactNode;
}

export const BaseLayout = ({children}: BaseLayoutProps): any => {
  return (
    <div
      className={
        vstack({
          alignItems: 'center',
        })
      }
    >
      <header className={layoutChild}>

      </header>

      <main className={layoutChild}>
        {children}
      </main>

      <footer className={layoutChild}>
        <span>
          &copy; ilfey
        </span>
      </footer>
    </div>
  );
};

const layoutChild = box({
  maxW: 1440,
  w: '100%',
  marginInline: 'auto',
});

// src/shared/widgets/BaseLayout/BaseLayout.vue
<script
  setup
  lang="ts"
>
import {box} from 'generated/patterns/box';
import {vstack} from 'generated/patterns/vstack';

const layoutChild = box({
  maxW: 1440,
  marginInline: 'auto',
});
</script>

<template>
  <div
    :class="vstack({
    alignItems: 'center',
  })"
  >
    <header
      :class="layoutChild"
    >

    </header>
    <main :class="layoutChild">
      <slot />
    </main>
    <footer :class="layoutChild">
      <span>
        &copy; ilfey
      </span>
    </footer>
  </div>
</template>
